import type { VoiceExtractedProfile } from "@/modules/voice/types";

/** Arjun Sharma — strong-CRS Indian FSW candidate for Express Entry. Dev use only. */
export const MOCK_IMMIGRATION_PROFILE = {
  full_name: "Arjun Sharma",
  date_of_birth: "1996-05-15",
  nationality: "Indian",
  current_country: "India",
  marital_status: "married",
  education_level_voice: "Bachelor's degree in Computer Science",
  years_experience: 5,
  has_canadian_experience: false,
  occupation: "Software Engineer",
  language_proficiency_self: "fluent" as const,
  has_family_in_canada: false,
  intended_province: null,
  annual_income: 2500000,
  income_currency: "INR",
  // IELTS: L 8.5 → CLB 10, R 8.0 → CLB 10, S 7.5 → CLB 9, W 7.0 → CLB 9
  clb_listening: 10,
  clb_reading: 10,
  clb_speaking: 9,
  clb_writing: 9,
  canadian_work_years: 0,
  foreign_work_years: 5,
  canadian_work_recent: false,
  foreign_work_recent: true,
  noc_teer_category: 1,
  noc_code: "21232",
  education_level: "bachelors" as const,
  eca_obtained: true,
  spouse_coming_to_canada: true,
  spouse_education_level: "bachelors" as const,
  spouse_clb_listening: 7,
  spouse_clb_reading: 7,
  spouse_clb_speaking: 7,
  spouse_clb_writing: 7,
  spouse_canadian_work_years: 0,
  has_provincial_nomination: false,
  has_canadian_job_offer: false,
  has_sibling_in_canada: false,
  destination_country: "Canada",
  purpose: "Permanent Residency via Express Entry FSW",
  dependents: 1,
  requires_review: [],
} satisfies VoiceExtractedProfile;
