import type { Application } from './types';

/** Mock application — loaded when ?mock=true or applicationId is 'mock-1'. */
export const mockApplication: Application = {
  id: 'mock-application-1',
  pathway: {
    slug: 'express-entry-fsw',
    title: 'Federal Skilled Worker Program',
    official_name: 'Federal Skilled Worker Program (FSWP)',
  },
  status: 'in_progress',
  steps: [
    {
      id: 'step-1',
      step_number: 1,
      title: 'Check FSW 67-point eligibility',
      description: 'Verify you score at least 67/100 on the FSW selection grid.',
      type: 'information',
      status: 'completed',
      estimated_duration: '1 day',
      is_optional: false,
    },
    {
      id: 'step-2',
      step_number: 2,
      title: 'Language test results',
      description: 'Upload your IELTS, CELPIP, TEF, or TCF results. Must be less than 2 years old.',
      type: 'document_upload',
      status: 'current',
      estimated_duration: '4–8 weeks',
      is_optional: false,
      document: {
        name: 'Language Test Results',
        description:
          'IELTS General Training, CELPIP General, TEF Canada, or TCF Canada showing CLB 7 or above in all four abilities.',
        document_type: 'language_test',
        validity_period: '2 years',
        accepted_formats: ['PDF', 'JPG', 'PNG'],
        max_size_mb: 10,
      },
    },
    {
      id: 'step-3',
      step_number: 3,
      title: 'Educational Credential Assessment',
      description: 'Get your foreign degree assessed by WES or another designated body.',
      type: 'document_upload',
      status: 'upcoming',
      estimated_duration: '4–8 weeks',
      is_optional: false,
      document: {
        name: 'ECA Report',
        description:
          'ECA from WES, IQAS, ICAS, or another IRCC-designated organisation.',
        document_type: 'eca_report',
        validity_period: '5 years',
        accepted_formats: ['PDF'],
        max_size_mb: 10,
      },
    },
    {
      id: 'step-4',
      step_number: 4,
      title: 'Employment reference letters',
      description: 'Collect letters from each employer covering the last 10 years.',
      type: 'document_upload',
      status: 'upcoming',
      estimated_duration: '2–4 weeks',
      is_optional: false,
      document: {
        name: 'Employment Reference Letters',
        description:
          'On company letterhead, confirming job title, duties, hours per week, salary, and dates.',
        document_type: 'employment_reference',
        validity_period: null,
        accepted_formats: ['PDF', 'JPG', 'PNG'],
        max_size_mb: 10,
      },
    },
    {
      id: 'step-5',
      step_number: 5,
      title: 'Proof of settlement funds',
      description: 'Bank statements showing at least $14,690 CAD.',
      type: 'document_upload',
      status: 'upcoming',
      estimated_duration: '1 week',
      is_optional: false,
      document: {
        name: 'Bank Statements',
        description:
          'Showing sufficient funds held for at least 6 months. Single applicant: $14,690 CAD minimum.',
        document_type: 'bank_statement',
        validity_period: '6 months',
        accepted_formats: ['PDF'],
        max_size_mb: 10,
      },
    },
    {
      id: 'step-6',
      step_number: 6,
      title: 'Create Express Entry profile',
      description:
        'Submit your profile on the IRCC portal. Your CRS score is assigned automatically.',
      type: 'external_action',
      status: 'upcoming',
      estimated_duration: '1–2 days',
      is_optional: false,
    },
    {
      id: 'step-7',
      step_number: 7,
      title: 'Enter the pool & await ITA',
      description: 'Your profile is live. Monitor your CRS score and draw results.',
      type: 'external_action',
      status: 'upcoming',
      estimated_duration: '1–12 months',
      is_optional: false,
    },
    {
      id: 'step-8',
      step_number: 8,
      title: 'Submit e-APR within 60 days',
      description:
        'Upload all documents through the IRCC portal after receiving your ITA.',
      type: 'review',
      status: 'upcoming',
      estimated_duration: '2–4 weeks',
      is_optional: false,
    },
    {
      id: 'step-9',
      step_number: 9,
      title: 'Biometrics & medical exam',
      description: 'Complete fingerprints and medical examination.',
      type: 'external_action',
      status: 'upcoming',
      estimated_duration: '2–4 weeks',
      is_optional: false,
    },
    {
      id: 'step-10',
      step_number: 10,
      title: 'Receive Confirmation of PR',
      description: 'IRCC issues your COPR. Land in Canada before expiry.',
      type: 'external_action',
      status: 'upcoming',
      estimated_duration: '1–6 months',
      is_optional: false,
    },
  ],
};
